"""
Django settings for fashionshop project.
Generated by 'django-admin startproject' (updated for allauth & Heroku).
"""

from pathlib import Path
import os

from dotenv import load_dotenv
import dj_database_url

# -----------------------------------------------------
# Base & environment
# -----------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env locally (harmless on Heroku if missing)
load_dotenv(BASE_DIR / ".env")

SECRET_KEY = os.getenv("SECRET_KEY", "dev-not-secure")
DEBUG = os.getenv("DEBUG", "False").lower() in {"1", "true", "yes"}
DJANGO_ENV = os.getenv("DJANGO_ENV", "production").lower()  # "local" or "production"

# Hosts & CSRF (comma-separated env values)
ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if h.strip()
]
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

# -----------------------------------------------------
# Stripe (optional)
# -----------------------------------------------------
STRIPE_SECRET_KEY      = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_WEBHOOK_SECRET  = os.getenv("STRIPE_WEBHOOK_SECRET", "")
STRIPE_CURRENCY        = os.getenv("STRIPE_CURRENCY", "gbp")

# -----------------------------------------------------
# Apps / Middleware
# -----------------------------------------------------
INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",

    # Third-party
    "allauth",
    "allauth.account",
    "allauth.socialaccount",

    # Local apps
    "catalog",
    "home",
    "orders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "fashionshop.urls"
WSGI_APPLICATION = "fashionshop.wsgi.application"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            BASE_DIR / "templates" / "allauth",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
                # custom
                "catalog.context_processors.bag_summary",
            ],
        },
    },
]

# -----------------------------------------------------
# Auth / Allauth (no deprecations)
# -----------------------------------------------------
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

SITE_ID = int(os.getenv("SITE_ID", "1"))

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend"
)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@localhost")

# ✅ New-style allauth config
# Fields on the signup form (asterisk = required)
ACCOUNT_SIGNUP_FIELDS = [
    "email*", "email2*",
    "username*",
    "password1*", "password2*",
]

# Other knobs
ACCOUNT_USERNAME_MIN_LENGTH = 4
LOGIN_URL = "account_login"
LOGIN_REDIRECT_URL = "/"

# -----------------------------------------------------
# Database (Postgres via DATABASE_URL; local SQLite fallback)
# -----------------------------------------------------
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
PG_SCHEMA = os.getenv("POSTGRES_SCHEMA", "fashionshop")

# Control SSL via env: default OFF in DEBUG, ON otherwise
DB_SSL_REQUIRE = os.getenv("DB_SSL_REQUIRE", "false" if DEBUG else "true").lower() in {"1", "true", "yes"}

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=DB_SSL_REQUIRE,
        )
    }
    # If this is Postgres, set the search_path so your app tables prefer PG_SCHEMA
    if DATABASES["default"]["ENGINE"].startswith("django.db.backends.postgresql"):
        DATABASES["default"].setdefault("OPTIONS", {})
        DATABASES["default"]["OPTIONS"]["options"] = f"-c search_path={PG_SCHEMA},public"
else:
    # Local dev fallback
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# -----------------------------------------------------
# Static / Media (WhiteNoise)
# -----------------------------------------------------
STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    }
}

# -----------------------------------------------------
# i18n / tz
# -----------------------------------------------------
LANGUAGE_CODE = "en-gb"
TIME_ZONE = os.getenv("TIME_ZONE", "Europe/London")
USE_I18N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -----------------------------------------------------
# Production hardening
# -----------------------------------------------------
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30  # 30 days
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Behind Heroku’s proxy/load balancer
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
