# Generated by Django 4.2.23 on 2025-10-26 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('email', models.TextField(db_column='email')),
                ('full_name', models.CharField(blank=True, db_column='full_name', max_length=120, null=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
            ],
            options={
                'db_table': '"fashionshop"."app_user"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_column='status', default='pending', max_length=20)),
                ('total_amount', models.DecimalField(db_column='total_amount', decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, editable=False)),
                ('buyer_name', models.TextField(blank=True, db_column='buyer_name', null=True)),
                ('buyer_email', models.TextField(blank=True, db_column='buyer_email', null=True)),
                ('buyer_phone', models.TextField(blank=True, db_column='buyer_phone', null=True)),
                ('ship_address1', models.TextField(blank=True, db_column='ship_address1', null=True)),
                ('ship_address2', models.TextField(blank=True, db_column='ship_address2', null=True)),
                ('ship_city', models.TextField(blank=True, db_column='ship_city', null=True)),
                ('ship_postcode', models.TextField(blank=True, db_column='ship_postcode', null=True)),
                ('ship_country', models.TextField(blank=True, db_column='ship_country', null=True)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
            ],
            options={
                'db_table': '"fashionshop"."order"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(db_column='quantity')),
                ('price_each', models.DecimalField(db_column='price_each', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': '"fashionshop"."order_item"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_column='provider', max_length=40)),
                ('method', models.CharField(choices=[('card', 'Card'), ('paypal', 'PayPal'), ('cod', 'Cash on Delivery')], db_column='method', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], db_column='status', max_length=20)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, max_digits=10)),
                ('provider_ref', models.CharField(blank=True, db_column='provider_ref', max_length=200, null=True)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': '"fashionshop"."payment"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(db_column='from_status', max_length=20)),
                ('to_status', models.CharField(db_column='to_status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'db_table': '"fashionshop"."order_status_history"',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
